services:
  # FPM
  php_fpm:
    build:
      context: ../
      dockerfile: .docker/fpm/Dockerfile
    volumes:
      - ./fpm/www-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ../:/var/www
    networks:
      - integration_api

  nginx_fpm:
    image: nginx:latest
    volumes:
      - ./fpm/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9001:9001
    networks:
      - integration_api

  # Swoole
  php_swoole:
    build:
      context: ../
      dockerfile: .docker/swoole/Dockerfile
    volumes:
      - ../:/var/www
      - ./logs:/var/log
    environment:
      - APP_RUNTIME:"Runtime\\Swoole\\Runtime"
    networks:
      - integration_api

  nginx_swoole:
    image: nginx:latest
    volumes:
      - ./swoole/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9002:9002
    networks:
      - integration_api

  # Road Runner
  php_roadrunner:
    build:
      context: ../
      dockerfile: .docker/roadrunner/Dockerfile
    volumes:
      - docker_roadrunner_bin:/var/www/bin-roadrunner
      - ../:/var/www
      - ./logs:/var/log
    ports:
      - 9003:9003
    networks:
      - integration_api

  # Nginx Unit
  php_nginx_unit:
    build:
      context: ../
      dockerfile: .docker/nginx-unit/Dockerfile
    volumes:
      - ../:/var/www
      - ./logs:/var/log
    ports:
      - 9004:9004
    networks:
      - integration_api

secrets:
  composer_auth:
    file: ../auth.json

networks:
  integration_api:

volumes:
  docker_roadrunner_bin:
